//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyDatabaseEntities : DbContext
    {
        private static CompanyDatabaseEntities _context; 
        public CompanyDatabaseEntities()
            : base("name=CompanyDatabaseEntities")
        {
        }

        public static CompanyDatabaseEntities GetContext()
        {
            if (_context == null)
                _context = new CompanyDatabaseEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Leaders> Leaders { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trainees> Trainees { get; set; }
        public virtual DbSet<СompanyEmployees> СompanyEmployees { get; set; }
    }
}
